from __future__ import annotations

import datetime as dt
import json
import re
from pathlib import Path
from typing import Any

from . import VERSION
from .contracts import resolve_slicer_contract, validate_contract
from .core import sha256_file
from .errors import GuardianError
from .limits import ResourceLimits

SLICER_REPORT_SCHEMA_URI = (
    "https://raw.githubusercontent.com/alexd-za/codex-skills/main/skills/"
    "fusion-cad-guardian/schemas/slicer-report.schema.json"
)

_TIME_RE = re.compile(
    r"(?:(?P<days>\d+)d\s*)?(?:(?P<hours>\d+)h\s*)?(?:(?P<minutes>\d+)m\s*)?(?:(?P<seconds>\d+(?:\.\d+)?)s)?",
    re.IGNORECASE,
)
_FLOAT = r"([-+]?\d+(?:\.\d+)?)"


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def _duration_seconds(value: str) -> float | None:
    value = value.strip()
    if value.isdigit():
        return float(value)
    match = _TIME_RE.fullmatch(value)
    if not match or not any(match.groupdict().values()):
        return None
    groups = {key: float(item or 0) for key, item in match.groupdict().items()}
    return groups["days"] * 86400 + groups["hours"] * 3600 + groups["minutes"] * 60 + groups["seconds"]


def _first_float(value: str) -> float | None:
    match = re.search(_FLOAT, value)
    return float(match.group(1)) if match else None


def _parse_float_list(value: str) -> list[float]:
    return [float(item) for item in re.findall(_FLOAT, value)]


def parse_gcode_metadata(path: Path, *, limits: ResourceLimits | None = None) -> tuple[dict[str, Any], dict[str, Any]]:
    active = (limits or ResourceLimits()).validate()
    if not path.is_file():
        raise GuardianError(f"G-code file not found: {path}")
    size = path.stat().st_size
    if size > int(active.max_file_size_mb * 1024 * 1024):
        raise GuardianError(
            f"G-code size {size} bytes exceeds max_file_size_mb={active.max_file_size_mb:g}"
        )

    metadata: dict[str, Any] = {
        "generator": None,
        "estimated_print_time_seconds": None,
        "filament_used_mm": None,
        "filament_used_cm3": None,
        "filament_used_g": None,
        "layer_count": None,
        "layer_height_mm": None,
        "first_layer_height_mm": None,
        "nozzle_diameters_mm": [],
        "max_z_mm": None,
    }
    layer_markers: set[int] = set()
    lines_read = 0
    comment_lines = 0
    patterns = {
        "generator": [r"^;\s*generated by\s+(.+)$", r"^;\s*generated with\s+(.+)$"],
        "estimated_print_time_seconds": [
            r"^;\s*estimated printing time(?:\s*\([^)]*\))?\s*=\s*(.+)$",
            r"^;\s*total estimated time\s*[:=]\s*(.+)$",
            r"^;\s*model printing time\s*[:=]\s*(.+)$",
        ],
        "filament_used_mm": [r"^;\s*(?:total )?filament used \[mm\]\s*=\s*(.+)$"],
        "filament_used_cm3": [r"^;\s*(?:total )?filament used \[cm3\]\s*=\s*(.+)$"],
        "filament_used_g": [
            r"^;\s*(?:total )?filament used \[g\]\s*=\s*(.+)$",
            r"^;\s*filament used\s*[:=].*?" + _FLOAT + r"\s*g\b.*$",
        ],
        "layer_count": [
            r"^;\s*total layer number\s*[:=]\s*(\d+)",
            r"^;\s*layer_count\s*=\s*(\d+)",
        ],
        "layer_height_mm": [r"^;\s*layer_height\s*=\s*(.+)$"],
        "first_layer_height_mm": [r"^;\s*first_layer_height\s*=\s*(.+)$"],
        "nozzle_diameters_mm": [r"^;\s*nozzle_diameter\s*=\s*(.+)$"],
        "max_z_mm": [r"^;\s*max_z_height\s*[:=]\s*(.+)$"],
    }

    try:
        handle = path.open("r", encoding="utf-8-sig", errors="replace")
    except OSError as exc:
        raise GuardianError(f"cannot read G-code: {path}") from exc
    with handle:
        for line in handle:
            lines_read += 1
            stripped = line.strip()
            if stripped.startswith(";"):
                comment_lines += 1
                layer_match = re.match(r"^;\s*LAYER\s*[:=]\s*(-?\d+)", stripped, re.IGNORECASE)
                if layer_match:
                    layer_markers.add(int(layer_match.group(1)))
                for key, expressions in patterns.items():
                    if metadata[key] not in (None, []):
                        continue
                    for expression in expressions:
                        match = re.match(expression, stripped, re.IGNORECASE)
                        if not match:
                            continue
                        value = match.group(1).strip()
                        if key == "generator":
                            metadata[key] = value[:500]
                        elif key == "estimated_print_time_seconds":
                            metadata[key] = _duration_seconds(value)
                        elif key == "layer_count":
                            metadata[key] = int(_first_float(value) or 0)
                        elif key == "nozzle_diameters_mm":
                            metadata[key] = _parse_float_list(value)
                        else:
                            values = _parse_float_list(value)
                            metadata[key] = sum(values) if key.startswith("filament_used") and values else (_first_float(value))
                        break
            if stripped.startswith("G1") and " Z" in f" {stripped}":
                match = re.search(r"(?:^|\s)Z" + _FLOAT, stripped, re.IGNORECASE)
                if match:
                    z_value = float(match.group(1))
                    if metadata["max_z_mm"] is None or z_value > metadata["max_z_mm"]:
                        metadata["max_z_mm"] = z_value

    if metadata["layer_count"] is None and layer_markers:
        non_negative = [item for item in layer_markers if item >= 0]
        if non_negative:
            metadata["layer_count"] = max(non_negative) + 1
    metadata["nozzle_diameters_mm"] = sorted(set(metadata["nozzle_diameters_mm"] or []))
    detected = [key for key, value in metadata.items() if value not in (None, [], "")]
    preflight = {
        "size_bytes": size,
        "lines_read": lines_read,
        "comment_lines": comment_lines,
        "detected_fields": detected,
        "limits": active.to_dict(),
    }
    return metadata, preflight


def _range_check(value: float, requirement: dict[str, Any]) -> tuple[bool, str]:
    if "target" in requirement:
        target = float(requirement["target"])
        tolerance = float(requirement["tolerance"])
        return abs(value - target) <= tolerance, f"{target} ± {tolerance}"
    minimum = requirement.get("min")
    maximum = requirement.get("max")
    ok = (minimum is None or value >= float(minimum)) and (maximum is None or value <= float(maximum))
    expected = f"{minimum if minimum is not None else '-∞'} .. {maximum if maximum is not None else '∞'}"
    return ok, expected


def evaluate_slicer_contract(metadata: dict[str, Any], rules: dict[str, Any] | None) -> list[dict[str, Any]]:
    if not rules:
        return []
    checks: list[dict[str, Any]] = []
    mapping = {
        "print_time_seconds": "estimated_print_time_seconds",
        "filament_mm": "filament_used_mm",
        "filament_cm3": "filament_used_cm3",
        "filament_g": "filament_used_g",
        "layer_count": "layer_count",
        "layer_height_mm": "layer_height_mm",
        "first_layer_height_mm": "first_layer_height_mm",
        "max_z_mm": "max_z_mm",
    }
    for rule_name, metric_name in mapping.items():
        if rule_name not in rules:
            continue
        actual = metadata.get(metric_name)
        if actual is None:
            checks.append({"id": f"slicer.{rule_name}", "status": "FAIL", "actual": "missing", "expected": str(rules[rule_name])})
            continue
        ok, expected = _range_check(float(actual), rules[rule_name])
        checks.append({"id": f"slicer.{rule_name}", "status": "PASS" if ok else "FAIL", "actual": actual, "expected": expected})
    if "allowed_nozzle_diameters_mm" in rules:
        actual_nozzles = metadata.get("nozzle_diameters_mm") or []
        allowed = [float(item) for item in rules["allowed_nozzle_diameters_mm"]]
        ok = bool(actual_nozzles) and all(any(abs(actual - item) <= 1e-6 for item in allowed) for actual in actual_nozzles)
        checks.append({
            "id": "slicer.allowed_nozzle_diameters_mm",
            "status": "PASS" if ok else "FAIL",
            "actual": actual_nozzles or "missing",
            "expected": allowed,
        })
    required_fields = rules.get("required_metadata_fields", [])
    for field in required_fields:
        value = metadata.get(field)
        checks.append({
            "id": f"slicer.metadata.{field}",
            "status": "PASS" if value not in (None, [], "") else "FAIL",
            "actual": value if value not in (None, [], "") else "missing",
            "expected": "present",
        })
    return checks


def build_slicer_report(
    gcode_path: Path,
    *,
    source_mesh_path: Path | None = None,
    part_id: str | None = None,
    slicer_rules: dict[str, Any] | None = None,
    contract_path: Path | None = None,
    limits: ResourceLimits | None = None,
) -> dict[str, Any]:
    contract_identity = {"path": None, "sha256": None, "part_id": part_id}
    if contract_path:
        try:
            contract = validate_contract(json.loads(contract_path.read_text(encoding="utf-8")))
        except FileNotFoundError as exc:
            raise GuardianError(f"contract file not found: {contract_path}") from exc
        except json.JSONDecodeError as exc:
            raise GuardianError(f"invalid contract JSON: {exc}") from exc
        resolved_rules, resolved_part = resolve_slicer_contract(contract, part_id)
        slicer_rules = resolved_rules
        part_id = resolved_part
        contract_identity = {
            "path": str(contract_path.resolve()),
            "sha256": sha256_file(contract_path),
            "part_id": part_id,
        }
    metadata, preflight = parse_gcode_metadata(gcode_path, limits=limits)
    checks = evaluate_slicer_contract(metadata, slicer_rules)
    verdict = "FAIL" if any(item["status"] == "FAIL" for item in checks) else ("PASS" if checks else "EVIDENCE_ONLY")
    source_mesh = None
    if source_mesh_path:
        if not source_mesh_path.is_file():
            raise GuardianError(f"source mesh not found: {source_mesh_path}")
        source_mesh = {
            "path": str(source_mesh_path.resolve()),
            "sha256": sha256_file(source_mesh_path),
            "size_bytes": source_mesh_path.stat().st_size,
        }
    return {
        "$schema": SLICER_REPORT_SCHEMA_URI,
        "guardian_version": VERSION,
        "generated_at": utc_now(),
        "part_id": part_id,
        "contract": contract_identity,
        "gcode": {
            "path": str(gcode_path.resolve()),
            "sha256": sha256_file(gcode_path),
            "size_bytes": gcode_path.stat().st_size,
        },
        "source_mesh": source_mesh,
        "preflight": preflight,
        "metadata": metadata,
        "checks": checks,
        "verdict": verdict,
        "limitations": [
            "G-code metadata is slicer-generated evidence, not proof of physical print success.",
            "Guardian does not execute slicers or trust metadata as a substitute for Fusion geometry evidence.",
            "Missing comments may mean the slicer omitted metadata rather than that the value is zero.",
        ],
    }


def _is_sha256(value: Any) -> bool:
    return isinstance(value, str) and bool(re.fullmatch(r"[0-9a-f]{64}", value))


def validate_slicer_report(report: Any) -> dict[str, Any]:
    if not isinstance(report, dict):
        raise GuardianError("slicer report must be an object")
    required = {
        "guardian_version", "generated_at", "part_id", "contract", "gcode",
        "source_mesh", "preflight", "metadata", "checks", "verdict", "limitations",
    }
    missing = required - set(report)
    if missing:
        raise GuardianError(f"slicer report is missing fields: {sorted(missing)}")
    if report.get("verdict") not in {"PASS", "FAIL", "EVIDENCE_ONLY"}:
        raise GuardianError("slicer report verdict is invalid")
    contract = report.get("contract")
    if not isinstance(contract, dict) or set(contract) != {"path", "sha256", "part_id"}:
        raise GuardianError("slicer report contract identity is invalid")
    if contract.get("sha256") is not None and not _is_sha256(contract.get("sha256")):
        raise GuardianError("slicer report contract SHA-256 is invalid")
    if contract.get("part_id") != report.get("part_id"):
        raise GuardianError("slicer report contract part identity does not match part_id")
    gcode = report.get("gcode")
    if not isinstance(gcode, dict) or not _is_sha256(gcode.get("sha256")):
        raise GuardianError("slicer report G-code identity is invalid")
    if not isinstance(gcode.get("path"), str) or not isinstance(gcode.get("size_bytes"), int) or gcode["size_bytes"] < 0:
        raise GuardianError("slicer report G-code path or size is invalid")
    source_mesh = report.get("source_mesh")
    if source_mesh is not None:
        if not isinstance(source_mesh, dict) or not _is_sha256(source_mesh.get("sha256")):
            raise GuardianError("slicer report source mesh identity is invalid")
        if not isinstance(source_mesh.get("path"), str) or not isinstance(source_mesh.get("size_bytes"), int) or source_mesh["size_bytes"] < 0:
            raise GuardianError("slicer report source mesh path or size is invalid")
    if not isinstance(report.get("checks"), list) or not isinstance(report.get("limitations"), list):
        raise GuardianError("slicer report checks and limitations must be arrays")
    return report
